import { Inter, Istok_Web } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

const istok_web = Istok_Web({
  style: ["normal", "italic"],
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Daily-life",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={istok_web.className}>{children}</body>
    </html>
  );
}
